# Generated by Django 4.2.7 on 2025-10-15 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('extension', models.CharField(max_length=10)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('snippets_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('code', models.TextField()),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='public', max_length=10)),
                ('tags', models.JSONField(default=list)),
                ('views_count', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('forks_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
                ('forked_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='snippets.snippet')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snippets', to='snippets.language')),
            ],
            options={
                'db_table': 'snippets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SnippetComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippet_comments', to=settings.AUTH_USER_MODEL)),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='snippets.snippet')),
            ],
            options={
                'db_table': 'snippet_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SnippetLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='snippets.snippet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippet_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'snippet_likes',
                'unique_together': {('user', 'snippet')},
            },
        ),
        migrations.AddIndex(
            model_name='snippet',
            index=models.Index(fields=['slug'], name='snippets_slug_a952f1_idx'),
        ),
        migrations.AddIndex(
            model_name='snippet',
            index=models.Index(fields=['author', '-created_at'], name='snippets_author__a82cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='snippet',
            index=models.Index(fields=['language', '-created_at'], name='snippets_languag_041aea_idx'),
        ),
        migrations.AddIndex(
            model_name='snippet',
            index=models.Index(fields=['visibility', '-created_at'], name='snippets_visibil_b883f3_idx'),
        ),
    ]
