# ============================================================================
# .github/workflows/ci.yml (GitHub Actions)
# ============================================================================

name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres123
          POSTGRES_DB: DevConnect_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_NAME: DevConnect_db
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_HOST: localhost
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      REDIS_HOST: redis
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: True
      ALLOWED_HOSTS: localhost, 127.0.0.1

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: wait for redis to be ready
      run: |
        until redis-cli -h redis ping; do
          echo "Waiting for Redis..."
          sleep 1
        done
    - name: Run linting
      run: |
        pip install flake8
        flake8 apps --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 apps --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Run migrations
      env:
        DB_NAME: DevConnect_db
        DB_USER: postgres
        DB_PASSWORD: postgres123
        DB_HOST: localhost
        DB_PORT: 5432
        REDIS_URL: redis://localhost:6379/0
        CELERY_BROKER_URL: redis://localhost:6379/0
        CELERY_RESULT_BACKEND: redis://localhost:6379/0
        REDIS_HOST: redis
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: True
        ALLOWED_HOSTS: localhost, 127.0.0.1

      run: python manage.py migrate
    
    - name: Run tests with coverage
      env:
        DB_NAME: DevConnect_db
        DB_USER: postgres
        DB_PASSWORD: postgres123
        DB_HOST: localhost
        DB_PORT: 5432
        REDIS_URL: redis://redis:6379/0
        CELERY_BROKER_URL: redis://redis:6379/0
        CELERY_RESULT_BACKEND: redis://redis:6379/0
        REDIS_HOST: redis
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: True
        ALLOWED_HOSTS: localhost, 127.0.0.1
      run: pytest --cov --cov-report=xml --cov-report=term
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build -t DevConnect:latest .
    
    - name: Log build success
      run: echo "Docker image built successfully"